package miniproject;
import miniproject.ManagerFrame;
import javax.swing.JOptionPane;
import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author shreeharini
 */
public class EmployeeManage extends javax.swing.JFrame {
    Employee e=new Employee();
    /**
     * Creates new form EmployeeManage
     */
    public EmployeeManage() {
        initComponents();
        try { 
            showEmployee();
        } catch (SQLException ex) {
            Logger.getLogger(EmployeeManage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        Heading = new javax.swing.JPanel();
        Emphead = new javax.swing.JLabel();
        Backbutt = new javax.swing.JButton();
        Empdnam = new javax.swing.JLabel();
        Empnamtext = new javax.swing.JTextField();
        Role = new javax.swing.JLabel();
        Conta = new javax.swing.JLabel();
        Contattext = new javax.swing.JTextField();
        Insertbutt = new javax.swing.JButton();
        Editbutt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Protable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        Delbutt = new javax.swing.JButton();
        Rolecombo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Heading.setBackground(new java.awt.Color(51, 204, 255));
        Heading.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Emphead.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Emphead.setText("EMPLOYEE MANAGEMENT");
        Heading.add(Emphead, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, -1, -1));

        Backbutt.setBackground(new java.awt.Color(0, 204, 255));
        Backbutt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Backbutt.setIcon(new javax.swing.ImageIcon("C:\\Users\\aaksh\\Downloads\\icons8-back-48.png")); // NOI18N
        Backbutt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, null));
        Backbutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbuttActionPerformed(evt);
            }
        });
        Heading.add(Backbutt, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 70, 40));

        Background.add(Heading, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 120));

        Empdnam.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Empdnam.setText("EMPLOYEE NAME");
        Background.add(Empdnam, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, -1, 30));

        Empnamtext.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Empnamtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpnamtextActionPerformed(evt);
            }
        });
        Background.add(Empnamtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 120, 40));

        Role.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Role.setText("ROLE");
        Background.add(Role, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        Conta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Conta.setText("CONTACT");
        Background.add(Conta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, -1));

        Contattext.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Background.add(Contattext, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 130, 40));

        Insertbutt.setBackground(new java.awt.Color(0, 153, 255));
        Insertbutt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Insertbutt.setText("INSERT");
        Insertbutt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Insertbutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertbuttActionPerformed(evt);
            }
        });
        Background.add(Insertbutt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 80, 40));

        Editbutt.setBackground(new java.awt.Color(0, 153, 255));
        Editbutt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Editbutt.setText("EDIT");
        Editbutt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Editbutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditbuttActionPerformed(evt);
            }
        });
        Background.add(Editbutt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 600, 100, 40));

        Protable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 4));
        Protable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "EMP ID", "EMP NAME", "ROLE", "CONTACT"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Protable.setShowGrid(true);
        Protable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProtableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Protable);

        Background.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 530, 440));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("   EMPLOYEE DETAILS");
        Background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 190, 40));

        Delbutt.setBackground(new java.awt.Color(51, 153, 255));
        Delbutt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Delbutt.setText("DELETE");
        Delbutt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Delbutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelbuttActionPerformed(evt);
            }
        });
        Background.add(Delbutt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 520, 100, 40));

        Rolecombo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Rolecombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Resource Assistant", "Account Assistant", "Supervisor", "Designer", "Stage Assistant", " ", " " }));
        Rolecombo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Background.add(Rolecombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 160, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackbuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbuttActionPerformed
        // TODO add your handling code here:
        this.dispose(); // Close the current frame
        ManagerFrame m = new ManagerFrame(); // Create instance of ManagerFrame
        m.setVisible(true); // Show the Manager frame
    }//GEN-LAST:event_BackbuttActionPerformed

    private void EmpnamtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpnamtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmpnamtextActionPerformed

    private int updateEmpId = -1;
    private void EditbuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditbuttActionPerformed
        // TODO add your handling code here:
       try {
        if (updateEmpId == -1) {
            // First Step: Fetch employee details
            String empIdInput = JOptionPane.showInputDialog(null, "Enter Employee ID to Update:");

            if (empIdInput != null && !empIdInput.trim().isEmpty()) {
                int empId = Integer.parseInt(empIdInput);

                Connection conn = e.getConnection();
                String selectSql = "SELECT ename, role, contact FROM employees WHERE eid=?";
                PreparedStatement selectStmt = conn.prepareStatement(selectSql);
                selectStmt.setInt(1, empId);
                ResultSet rs = selectStmt.executeQuery();

                if (rs.next()) {
                    // Set data into text fields
                    Empnamtext.setText(rs.getString("ename"));
                    Rolecombo.setSelectedItem(rs.getString("role"));
                    Contattext.setText(String.valueOf(rs.getLong("contact")));

                    updateEmpId = empId; // Store ID for next update
                    JOptionPane.showMessageDialog(null, "Employee details loaded.\nNow edit the fields and click UPDATE again.");
                } else {
                    JOptionPane.showMessageDialog(null, "Employee ID not found.");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Employee ID is required.");
            }
        } 
        else {
            // Second Step: Update employee details
            Connection conn = e.getConnection();
            String updateSql = "UPDATE employees SET ename=?, role=?, contact=? WHERE eid=?";
            PreparedStatement updateStmt = conn.prepareStatement(updateSql);

            updateStmt.setString(1, Empnamtext.getText());
            updateStmt.setString(2, Rolecombo.getSelectedItem().toString());
            updateStmt.setLong(3, Long.parseLong(Contattext.getText()));
            updateStmt.setInt(4, updateEmpId);

            int rowsAffected = updateStmt.executeUpdate();
            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(null, "Employee Updated Successfully");
                showEmployee(); // Refresh table

                // Clear fields after update
                Empnamtext.setText("");
                Rolecombo.setSelectedIndex(0);
                Contattext.setText("");
                updateEmpId = -1; // Reset for next update
            } else {
                JOptionPane.showMessageDialog(null, "Update Failed");
            }
        }
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(null, "Invalid Employee ID format. Please enter a valid number.");
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
        ex.printStackTrace();
    }
    }//GEN-LAST:event_EditbuttActionPerformed

    private void InsertbuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertbuttActionPerformed
        // TODO add your handling code here:
    String empName = Empnamtext.getText().trim();
    String role =Rolecombo.getSelectedItem().toString();
    String contactStr = Contattext.getText().trim();

    if (empName.isEmpty() || role.isEmpty() || contactStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill all fields.");
        return;
    }

    try {
        long contact = Long.parseLong(contactStr); // Validate contact number

        String insertQuery = "INSERT INTO employees (ename, role, contact) VALUES (?, ?, ?)";
        Employee db = new Employee();  // Create instance to connect
        Connection con = db.getConnection();
        
        PreparedStatement pt = con.prepareStatement(insertQuery);
        pt.setString(1, empName);
        pt.setString(2, role);
        pt.setLong(3, contact);

        int rowsAffected = pt.executeUpdate();
        if (rowsAffected > 0) {
            JOptionPane.showMessageDialog(this, "Employee added successfully!");

            // Clear fields after insert
            Empnamtext.setText("");
            Rolecombo.setSelectedIndex(0);
            Contattext.setText("");
            showEmployee();
        } else {
            JOptionPane.showMessageDialog(this, "Insert failed. Try again.");
        }

    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Contact must be a number.");
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Database error: " + ex.getMessage());
        ex.printStackTrace();
    }
    }//GEN-LAST:event_InsertbuttActionPerformed

    private void DelbuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelbuttActionPerformed
        // TODO add your handling code here:                                       
    try {
        // Prompt the user for the Employee ID
        String input = JOptionPane.showInputDialog(this, "Enter Employee ID to delete:");
        
        // If the user cancels or inputs nothing
        if (input == null || input.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Deletion cancelled or no ID entered.");
            return;
        }

        int empId = Integer.parseInt(input.trim());

        Connection conn = e.getConnection();  // Your DB connection method
        String sql = "DELETE FROM employees WHERE eid=?";
        PreparedStatement pt = conn.prepareStatement(sql);
        pt.setInt(1, empId);

        int rowsAffected = pt.executeUpdate();
        if (rowsAffected > 0) {
            JOptionPane.showMessageDialog(this, "Employee Deleted Successfully");
            showEmployee(); // Refresh table
        } else {
            JOptionPane.showMessageDialog(this, "Employee ID not found");
        }

        // Clear input fields
        Empnamtext.setText("");
        Rolecombo.setSelectedIndex(0);
        Contattext.setText("");

    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Invalid ID. Please enter a valid number.");
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Delete Error: " + ex.getMessage());
    }
    }//GEN-LAST:event_DelbuttActionPerformed

    private void ProtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProtableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ProtableMouseClicked

       private void showEmployee() throws SQLException {
        try{
        Connection conn = e.getConnection();
        String sql = "SELECT * FROM employees";
        PreparedStatement pt = conn.prepareStatement(sql);
        ResultSet rs = pt.executeQuery();
        DefaultTableModel model = (DefaultTableModel) Protable.getModel();
        model.setRowCount(0); // Clear table first

       while (rs.next()) {
        model.addRow(new Object[]{
        rs.getInt("eid"),
        rs.getString("ename"),
        rs.getString("role"),
        rs.getLong("contact")
    });
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Display Error: " + e.getMessage());
    }
 }      
    public class Employee{
        private Connection conn ;
        public Employee(){
             connectToDatabase();
        }    
    public void connectToDatabase() {
        try {
            // Load MySQL Driver
            Class.forName("com.mysql.cj.jdbc.Driver");
            // String url = "jdbc:mysql://localhost:3306/?user"; 
            String url = "jdbc:mysql://localhost:3306/SKFARTS?useSSL=false&allowPublicKeyRetrieval=true";  
            String user = "root"; 
            String password = "Harini@05";  

           
            conn = DriverManager.getConnection(url, user, password);
            System.out.println("Connected successfully!");
            JOptionPane.showMessageDialog(null, "Database connected successfully!");

        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, "MySQL JDBC Driver not found!");
            e.printStackTrace();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Database connection failed!\n" + e.getMessage());
            e.printStackTrace();
        }
    }
    public Connection getConnection() {
        return conn;
    }
 }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeManage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Backbutt;
    private javax.swing.JPanel Background;
    private javax.swing.JLabel Conta;
    private javax.swing.JTextField Contattext;
    private javax.swing.JButton Delbutt;
    private javax.swing.JButton Editbutt;
    private javax.swing.JLabel Empdnam;
    private javax.swing.JLabel Emphead;
    private javax.swing.JTextField Empnamtext;
    private javax.swing.JPanel Heading;
    private javax.swing.JButton Insertbutt;
    private javax.swing.JTable Protable;
    private javax.swing.JLabel Role;
    private javax.swing.JComboBox<String> Rolecombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
