/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package miniproject;

import javax.swing.JOptionPane;
/**
 *
 * @author shreeharini
 */
public class EmployeeFrame extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeFrame
     */
    public EmployeeFrame() {
        initComponents();
        setLocationRelativeTo(null);
         JOptionPane.showMessageDialog(this, "Welcome, Employee!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Topic = new javax.swing.JPanel();
        Empltopic = new javax.swing.JLabel();
        Logout = new javax.swing.JButton();
        Stockbutt = new javax.swing.JButton();
        Stockhead = new javax.swing.JLabel();
        Jobbutt = new javax.swing.JButton();
        Jobshead = new javax.swing.JLabel();
        Viewbutt = new javax.swing.JButton();
        Viewhead = new javax.swing.JLabel();
        Background = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Topic.setBackground(new java.awt.Color(102, 204, 255));
        Topic.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Empltopic.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        Empltopic.setText("EMPLOYEE WORKSPACE");
        Topic.add(Empltopic, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, -1, 40));

        getContentPane().add(Topic, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 150));

        Logout.setBackground(new java.awt.Color(204, 204, 204));
        Logout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Logout.setForeground(new java.awt.Color(255, 255, 255));
        Logout.setIcon(new javax.swing.ImageIcon("C:\\Users\\aaksh\\Downloads\\icons8-home-100.png")); // NOI18N
        Logout.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        getContentPane().add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 660, 120, 100));

        Stockbutt.setIcon(new javax.swing.ImageIcon("C:\\Users\\aaksh\\Downloads\\mpg4 (1).jpg")); // NOI18N
        Stockbutt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Stockbutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StockbuttActionPerformed(evt);
            }
        });
        getContentPane().add(Stockbutt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, 110, 90));

        Stockhead.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Stockhead.setText("   STOCK UPDATE");
        getContentPane().add(Stockhead, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 150, 50));

        Jobbutt.setBackground(new java.awt.Color(204, 204, 204));
        Jobbutt.setIcon(new javax.swing.ImageIcon("C:\\Users\\aaksh\\Downloads\\icons8-job-100.png")); // NOI18N
        Jobbutt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Jobbutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JobbuttActionPerformed(evt);
            }
        });
        getContentPane().add(Jobbutt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 130, 110));

        Jobshead.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Jobshead.setText("VIEW JOBS");
        getContentPane().add(Jobshead, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 110, 40));

        Viewbutt.setBackground(new java.awt.Color(204, 204, 204));
        Viewbutt.setIcon(new javax.swing.ImageIcon("C:\\Users\\aaksh\\Downloads\\icons8-view-70.png")); // NOI18N
        Viewbutt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Viewbutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewbuttActionPerformed(evt);
            }
        });
        getContentPane().add(Viewbutt, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 450, 120, 120));

        Viewhead.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Viewhead.setText("VIEW STOCK");
        getContentPane().add(Viewhead, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 410, 120, 20));

        Background.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 830, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
        this.dispose(); // Close the ManagerDashboard
        new LoginFrame().setVisible(true);
    }//GEN-LAST:event_LogoutActionPerformed

    private void StockbuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StockbuttActionPerformed
        // TODO add your handling code here:
        this.dispose(); // Close the ManagerDashboard
        new Stockmanage1().setVisible(true);
    }//GEN-LAST:event_StockbuttActionPerformed

    private void JobbuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JobbuttActionPerformed
        // TODO add your handling code here:
        this.dispose(); // Close the ManagerDashboard
        new DisplayTables().setVisible(true);
    }//GEN-LAST:event_JobbuttActionPerformed

    private void ViewbuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewbuttActionPerformed
        // TODO add your handling code here:
        this.dispose(); // Close the ManagerDashboard
        new ViewStock().setVisible(true);
    }//GEN-LAST:event_ViewbuttActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JLabel Empltopic;
    private javax.swing.JButton Jobbutt;
    private javax.swing.JLabel Jobshead;
    private javax.swing.JButton Logout;
    private javax.swing.JButton Stockbutt;
    private javax.swing.JLabel Stockhead;
    private javax.swing.JPanel Topic;
    private javax.swing.JButton Viewbutt;
    private javax.swing.JLabel Viewhead;
    // End of variables declaration//GEN-END:variables
}
