/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package miniproject;
import javax.swing.Timer;

/**
 *
 * @author shreeharini
 */
public class Frontframe extends javax.swing.JFrame {
    Timer timer;
    /**
     * Creates new form Frontframe
     */
    public Frontframe() {
        initComponents();
        startProgressBar();
    }
    private void startProgressBar() {
       
        Progress.setValue(0);

       
        timer = new Timer(50, e -> {
            int current = Progress.getValue();

           
            if (current < 100) {
                Progress.setValue(current + 1);
                 Icon2.setText(current + 1 + "%");
            } else {
              
                timer.stop();
                dispose();
                new LoginFrame().setVisible(true);
            }
        });

       
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        Mainheading = new javax.swing.JLabel();
        Suheading = new javax.swing.JLabel();
        Icon2 = new javax.swing.JLabel();
        Back = new javax.swing.JLabel();
        Progress = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Background.setBackground(new java.awt.Color(153, 204, 255));
        Background.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Mainheading.setBackground(new java.awt.Color(255, 255, 255));
        Mainheading.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        Mainheading.setText("SKF RESOURCE REGISTER");
        Background.add(Mainheading, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 640, -1));

        Suheading.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Suheading.setText("     WELCOME TO SKF  RR   ");
        Suheading.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                SuheadingComponentHidden(evt);
            }
        });
        Background.add(Suheading, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 450, -1));

        Icon2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Icon2.setText("       %");
        Background.add(Icon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 120, 40));

        Back.setIcon(new javax.swing.ImageIcon("C:\\Users\\aaksh\\Downloads\\P3.png")); // NOI18N
        Background.add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 330));

        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 330));

        Progress.setBackground(new java.awt.Color(255, 255, 255));
        Progress.setForeground(new java.awt.Color(102, 204, 255));
        Progress.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        Progress.setFocusCycleRoot(true);
        getContentPane().add(Progress, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 750, 60));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SuheadingComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_SuheadingComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_SuheadingComponentHidden

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frontframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frontframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frontframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frontframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frontframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Back;
    private javax.swing.JPanel Background;
    private javax.swing.JLabel Icon2;
    private javax.swing.JLabel Mainheading;
    private javax.swing.JProgressBar Progress;
    private javax.swing.JLabel Suheading;
    // End of variables declaration//GEN-END:variables
}
