/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package miniproject;
import javax.swing.JOptionPane;
import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;

/**
 *
 * @author shreeharini
 */
public class LoginFrame extends javax.swing.JFrame {
     loginform l=new loginform();

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
        setLocationRelativeTo(null);
        l.connectToDatabase();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Loginpannel = new javax.swing.JPanel();
        SKF = new javax.swing.JLabel();
        Username = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        Dialogue = new javax.swing.JLabel();
        Logbutton = new javax.swing.JButton();
        Register = new javax.swing.JButton();
        TOPIC = new javax.swing.JLabel();
        Usertext = new javax.swing.JTextField();
        Passfield = new javax.swing.JPasswordField();
        Showpassword = new javax.swing.JCheckBox();
        Rolelable = new javax.swing.JLabel();
        Rolecombobox = new javax.swing.JComboBox<>();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(2, 2));
        setPreferredSize(new java.awt.Dimension(1749, 980));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Loginpannel.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(102, 0, 102)));

        SKF.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        SKF.setForeground(new java.awt.Color(102, 0, 102));
        SKF.setText("   SKF");

        Username.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Username.setText("USERNAME");

        Password.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Password.setText("PASSWORD");

        Dialogue.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Dialogue.setText("   Dont't have a account ?");

        Logbutton.setBackground(new java.awt.Color(51, 0, 102));
        Logbutton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Logbutton.setForeground(new java.awt.Color(255, 255, 255));
        Logbutton.setText("LOGIN");
        Logbutton.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(102, 0, 0), new java.awt.Color(153, 0, 0)));
        Logbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogbuttonActionPerformed(evt);
            }
        });

        Register.setBackground(new java.awt.Color(102, 0, 102));
        Register.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Register.setForeground(new java.awt.Color(255, 255, 255));
        Register.setText("REGISTER");
        Register.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 0, 0), new java.awt.Color(102, 0, 0), new java.awt.Color(102, 0, 0), new java.awt.Color(153, 0, 0)));
        Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterActionPerformed(evt);
            }
        });

        TOPIC.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        TOPIC.setText("    LOGIN");

        Usertext.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(102, 0, 0)));
        Usertext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsertextActionPerformed(evt);
            }
        });

        Passfield.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(102, 0, 0)));

        Showpassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Showpassword.setText("Show Pasword");
        Showpassword.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(153, 0, 0)));
        Showpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowpasswordActionPerformed(evt);
            }
        });

        Rolelable.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Rolelable.setText("LOGIN AS");

        Rolecombobox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Rolecombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MANAGER", "EMPLOYEE", " " }));
        Rolecombobox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 3, true));
        Rolecombobox.setPreferredSize(new java.awt.Dimension(110, 24));

        javax.swing.GroupLayout LoginpannelLayout = new javax.swing.GroupLayout(Loginpannel);
        Loginpannel.setLayout(LoginpannelLayout);
        LoginpannelLayout.setHorizontalGroup(
            LoginpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginpannelLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(LoginpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginpannelLayout.createSequentialGroup()
                        .addGroup(LoginpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginpannelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(Showpassword))
                            .addGroup(LoginpannelLayout.createSequentialGroup()
                                .addGroup(LoginpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(LoginpannelLayout.createSequentialGroup()
                                        .addGap(70, 70, 70)
                                        .addComponent(Logbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(LoginpannelLayout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addComponent(Dialogue, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Register, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(LoginpannelLayout.createSequentialGroup()
                                        .addGap(117, 117, 117)
                                        .addGroup(LoginpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(SKF, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TOPIC, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(LoginpannelLayout.createSequentialGroup()
                        .addGroup(LoginpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LoginpannelLayout.createSequentialGroup()
                                .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Usertext, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(LoginpannelLayout.createSequentialGroup()
                                .addGroup(LoginpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Password)
                                    .addComponent(Rolelable, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(110, 110, 110)
                                .addGroup(LoginpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(LoginpannelLayout.createSequentialGroup()
                                        .addComponent(Rolecombobox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(65, 65, 65))
                                    .addComponent(Passfield))))
                        .addGap(51, 51, 51))))
        );
        LoginpannelLayout.setVerticalGroup(
            LoginpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginpannelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SKF, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(TOPIC, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(LoginpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Username)
                    .addComponent(Usertext, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(LoginpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Passfield, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Password))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Showpassword)
                .addGap(28, 28, 28)
                .addGroup(LoginpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginpannelLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(Rolecombobox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(Rolelable))
                .addGap(42, 42, 42)
                .addComponent(Logbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(LoginpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Dialogue, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Register, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        getContentPane().add(Loginpannel, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 510, 540));

        Background.setIcon(new javax.swing.ImageIcon("C:\\Users\\aaksh\\Downloads\\mpg1 (1).jpg")); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void UsertextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsertextActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_UsertextActionPerformed

    private void RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterActionPerformed
        // TODO add your handling code here:
         Registeration f=new Registeration();
        f.show();
        this.dispose();
    }//GEN-LAST:event_RegisterActionPerformed

    private void ShowpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowpasswordActionPerformed
         // TODO add your handling code here:
         if(Showpassword.isSelected()){
            Passfield.setEchoChar((char) 0); //show password
        }
        else{
            Passfield.setEchoChar('*');//Hide Password
         }
    }//GEN-LAST:event_ShowpasswordActionPerformed

    private void LogbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogbuttonActionPerformed
        // TODO add your handling code here:
        if(Usertext.getText().equals("")){
                  JOptionPane.showMessageDialog(null, "Please fill out username");
              }
              else if(Passfield.getText().equals("")){
                  JOptionPane.showMessageDialog(null,"Please fill out password");
              }
              else{
                  l.login();
                 
              }  
        this.dispose();
    }//GEN-LAST:event_LogbuttonActionPerformed

  public class loginform{
        private Connection conn ;
    public void connectToDatabase() {
        try {          
            Class.forName("com.mysql.cj.jdbc.Driver");

            
            String url = "jdbc:mysql://localhost:3306/SKFARTS?useSSL=false&allowPublicKeyRetrieval=true";  
            String user = "root"; 
            String password = "Harini@05";  

            // Establish Connection
            conn = DriverManager.getConnection(url, user, password);
            System.out.println("Connected successfully!");
            JOptionPane.showMessageDialog(null, "Database connected successfully!");

        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, "MySQL JDBC Driver not found!");
            e.printStackTrace();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Database connection failed!\n" + e.getMessage());
            e.printStackTrace();
        }
    }
    
    public void login(){
        String username=Usertext.getText();
        String password=Passfield.getText();
        String role = Rolecombobox.getSelectedItem().toString();
        try{
            String query="select * from users where username = ? and password= ? and role= ?";
            //prepareStatement pt=conn.prepareStatement(query);
            PreparedStatement pt = conn.prepareStatement(query);
            pt.setString(1,username);
            pt.setString(2,password);
            pt.setString(3, role);
            ResultSet rs=pt.executeQuery();
            
            if(rs.next()){
                if (role.equals("MANAGER")) {
                   ManagerFrame managerFrame = new ManagerFrame();
                   managerFrame.setVisible(true);
                }
                   else
                    {
                   EmployeeFrame employeeFrame = new EmployeeFrame();
                   employeeFrame.setVisible(true);
    }
            }else{
                JOptionPane.showMessageDialog(null, "invalid");
            }            
        }
        
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Login failed!\n" + e.getMessage());
            e.printStackTrace();
            
        }
    }}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LoginFrame loginFrame=new LoginFrame();
                loginFrame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Dialogue;
    private javax.swing.JButton Logbutton;
    private javax.swing.JPanel Loginpannel;
    private javax.swing.JPasswordField Passfield;
    private javax.swing.JLabel Password;
    private javax.swing.JButton Register;
    private javax.swing.JComboBox<String> Rolecombobox;
    private javax.swing.JLabel Rolelable;
    private javax.swing.JLabel SKF;
    private javax.swing.JCheckBox Showpassword;
    private javax.swing.JLabel TOPIC;
    private javax.swing.JLabel Username;
    private javax.swing.JTextField Usertext;
    // End of variables declaration//GEN-END:variables
}
