/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package miniproject;
import javax.swing.JOptionPane;
/**
 *
 * @author shreeharini
 */
public class ManagerFrame extends javax.swing.JFrame {   
    /**
     * Creates new form ManagerFrame
     */
    public ManagerFrame() {
        initComponents();
        setLocationRelativeTo(null);
        JOptionPane.showMessageDialog(this, "Welcome, Manager!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background1 = new javax.swing.JPanel();
        Topic = new javax.swing.JLabel();
        Background2 = new javax.swing.JPanel();
        Logout = new javax.swing.JButton();
        Emphead = new javax.swing.JLabel();
        Stockhead = new javax.swing.JLabel();
        Jobshead = new javax.swing.JLabel();
        Viewhead = new javax.swing.JLabel();
        Empbutt = new javax.swing.JButton();
        Stockbutt = new javax.swing.JButton();
        Jobbutt = new javax.swing.JButton();
        Viewbutt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Background1.setBackground(new java.awt.Color(153, 204, 255));
        Background1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(5, 5, 5), new java.awt.Color(5, 5, 5), new java.awt.Color(5, 5, 5), new java.awt.Color(5, 5, 5)));
        Background1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Topic.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        Topic.setText("MANAGER WORKSPACE");
        Background1.add(Topic, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 440, 70));

        getContentPane().add(Background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 150));

        Background2.setBackground(new java.awt.Color(255, 255, 255));
        Background2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logout.setBackground(new java.awt.Color(204, 204, 204));
        Logout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Logout.setForeground(new java.awt.Color(255, 255, 255));
        Logout.setIcon(new javax.swing.ImageIcon("C:\\Users\\aaksh\\Downloads\\icons8-home-100.png")); // NOI18N
        Logout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        Background2.add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 460, 130, 110));

        Emphead.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Emphead.setText("EMPLOYEE");
        Background2.add(Emphead, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 110, 30));

        Stockhead.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Stockhead.setText("   STOCK UPDATE");
        Background2.add(Stockhead, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 150, 30));

        Jobshead.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Jobshead.setText("JOBS");
        Background2.add(Jobshead, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 50, 60, 30));

        Viewhead.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Viewhead.setText("VIEW STOCK");
        Background2.add(Viewhead, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 240, 120, -1));

        Empbutt.setBackground(new java.awt.Color(204, 204, 204));
        Empbutt.setIcon(new javax.swing.ImageIcon("C:\\Users\\aaksh\\Downloads\\icons8-employee-100.png")); // NOI18N
        Empbutt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Empbutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpbuttActionPerformed(evt);
            }
        });
        Background2.add(Empbutt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 120, 110));

        Stockbutt.setBackground(new java.awt.Color(204, 204, 204));
        Stockbutt.setIcon(new javax.swing.ImageIcon("C:\\Users\\aaksh\\Downloads\\mpg4 (1).jpg")); // NOI18N
        Stockbutt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Stockbutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StockbuttActionPerformed(evt);
            }
        });
        Background2.add(Stockbutt, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, -1, -1));

        Jobbutt.setBackground(new java.awt.Color(204, 204, 204));
        Jobbutt.setIcon(new javax.swing.ImageIcon("C:\\Users\\aaksh\\Downloads\\icons8-job-100.png")); // NOI18N
        Jobbutt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Jobbutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JobbuttActionPerformed(evt);
            }
        });
        Background2.add(Jobbutt, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 90, 140, 120));

        Viewbutt.setBackground(new java.awt.Color(204, 204, 255));
        Viewbutt.setIcon(new javax.swing.ImageIcon("C:\\Users\\aaksh\\Downloads\\icons8-view-70.png")); // NOI18N
        Viewbutt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Viewbutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewbuttActionPerformed(evt);
            }
        });
        Background2.add(Viewbutt, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 270, 120, 100));

        getContentPane().add(Background2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1200, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
        this.dispose(); // Close the ManagerDashboard
        new LoginFrame().setVisible(true);
    }//GEN-LAST:event_LogoutActionPerformed

    private void StockbuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StockbuttActionPerformed
        // TODO add your handling code here:
        this.dispose(); // Close the ManagerDashboard
        new StockManage().setVisible(true);
    }//GEN-LAST:event_StockbuttActionPerformed

    private void EmpbuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpbuttActionPerformed
        // TODO add your handling code here:
       this.dispose(); // Close the ManagerDashboard
        new EmployeeManage().setVisible(true);
    }//GEN-LAST:event_EmpbuttActionPerformed

    private void JobbuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JobbuttActionPerformed
        // TODO add your handling code here:
        this.dispose(); // Close the ManagerDashboard
        new JobsManage().setVisible(true);
    }//GEN-LAST:event_JobbuttActionPerformed

    private void ViewbuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewbuttActionPerformed
        // TODO add your handling code here:
        this.dispose(); // Close the ManagerDashboard
        new ViewStockFrame().setVisible(true);
    }//GEN-LAST:event_ViewbuttActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background1;
    private javax.swing.JPanel Background2;
    private javax.swing.JButton Empbutt;
    private javax.swing.JLabel Emphead;
    private javax.swing.JButton Jobbutt;
    private javax.swing.JLabel Jobshead;
    private javax.swing.JButton Logout;
    private javax.swing.JButton Stockbutt;
    private javax.swing.JLabel Stockhead;
    private javax.swing.JLabel Topic;
    private javax.swing.JButton Viewbutt;
    private javax.swing.JLabel Viewhead;
    // End of variables declaration//GEN-END:variables
}
