/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package miniproject;
import javax.swing.JOptionPane;
import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
/*
 * @author shreeharini
 */
public class Registeration extends javax.swing.JFrame {
    registerform r=new registerform();
    /**
     * Creates new form Registeration
     */
    public Registeration() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundpannel = new javax.swing.JPanel();
        Background = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        Registerpannel = new javax.swing.JPanel();
        Registerlable = new javax.swing.JLabel();
        Namelable = new javax.swing.JLabel();
        Nametext = new javax.swing.JTextField();
        Emaillable = new javax.swing.JLabel();
        Emailtext = new javax.swing.JTextField();
        Genderpannel = new javax.swing.JLabel();
        Gendercombobox = new javax.swing.JComboBox<>();
        Phonenolable = new javax.swing.JLabel();
        Usernamepannel = new javax.swing.JLabel();
        Setpasspannel = new javax.swing.JLabel();
        Conpasslable = new javax.swing.JLabel();
        Phonetext = new javax.swing.JTextField();
        Usernametext = new javax.swing.JTextField();
        REgbutton = new javax.swing.JButton();
        Setpasstext = new javax.swing.JPasswordField();
        Conpasstext = new javax.swing.JPasswordField();
        showpass1 = new javax.swing.JCheckBox();
        showpass2 = new javax.swing.JCheckBox();
        Back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 0, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backgroundpannel.setBackground(new java.awt.Color(0, 0, 51));

        Background.setBackground(new java.awt.Color(51, 102, 255));
        Background.setText("jLabel1");

        Logo.setIcon(new javax.swing.ImageIcon("C:\\Users\\aaksh\\Downloads\\mgp2.png")); // NOI18N

        javax.swing.GroupLayout backgroundpannelLayout = new javax.swing.GroupLayout(backgroundpannel);
        backgroundpannel.setLayout(backgroundpannelLayout);
        backgroundpannelLayout.setHorizontalGroup(
            backgroundpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundpannelLayout.createSequentialGroup()
                .addGroup(backgroundpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundpannelLayout.createSequentialGroup()
                        .addGap(411, 411, 411)
                        .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundpannelLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        backgroundpannelLayout.setVerticalGroup(
            backgroundpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundpannelLayout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(Background)
                .addGap(37, 37, 37)
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(172, Short.MAX_VALUE))
        );

        getContentPane().add(backgroundpannel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 700));

        Registerpannel.setBackground(new java.awt.Color(255, 255, 255));

        Registerlable.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Registerlable.setText("  REGISTERATION");

        Namelable.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Namelable.setText("  NAME");

        Nametext.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 0), 4));
        Nametext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NametextActionPerformed(evt);
            }
        });

        Emaillable.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Emaillable.setText("EMAIL");

        Emailtext.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 0), 4));

        Genderpannel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Genderpannel.setText("GENDER");

        Gendercombobox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Gendercombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MALE", "FEMALE", "OTHER" }));
        Gendercombobox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 0), 4));
        Gendercombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GendercomboboxActionPerformed(evt);
            }
        });

        Phonenolable.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Phonenolable.setText("Phone No");

        Usernamepannel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Usernamepannel.setText("USERNAME");

        Setpasspannel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Setpasspannel.setText("SET PASSWORD");

        Conpasslable.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Conpasslable.setText("CONFRIM PASSWORD");

        Phonetext.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 0), 4));

        Usernametext.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 0), 4));

        REgbutton.setBackground(new java.awt.Color(0, 51, 153));
        REgbutton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        REgbutton.setForeground(new java.awt.Color(255, 255, 255));
        REgbutton.setText("REGISTER");
        REgbutton.setHideActionText(true);
        REgbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REgbuttonActionPerformed(evt);
            }
        });

        Setpasstext.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 0), 4));
        Setpasstext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SetpasstextActionPerformed(evt);
            }
        });

        Conpasstext.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 0), 4));

        showpass1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        showpass1.setText("Show");
        showpass1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 0), 2, true));
        showpass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpass1ActionPerformed(evt);
            }
        });

        showpass2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        showpass2.setText("Show");
        showpass2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpass2ActionPerformed(evt);
            }
        });

        Back.setBackground(new java.awt.Color(0, 51, 153));
        Back.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Back.setForeground(new java.awt.Color(255, 255, 255));
        Back.setText("BACK");
        Back.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RegisterpannelLayout = new javax.swing.GroupLayout(Registerpannel);
        Registerpannel.setLayout(RegisterpannelLayout);
        RegisterpannelLayout.setHorizontalGroup(
            RegisterpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterpannelLayout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(Registerlable, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(RegisterpannelLayout.createSequentialGroup()
                .addGroup(RegisterpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegisterpannelLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(RegisterpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Usernamepannel)
                            .addComponent(Setpasspannel)
                            .addComponent(Phonenolable)
                            .addComponent(Genderpannel)
                            .addComponent(Emaillable, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(RegisterpannelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(Conpasslable))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegisterpannelLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(Namelable, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)))
                .addGroup(RegisterpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegisterpannelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(RegisterpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Emailtext, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                            .addGroup(RegisterpannelLayout.createSequentialGroup()
                                .addGroup(RegisterpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Usernametext, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Gendercombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Phonetext, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Nametext, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(RegisterpannelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(RegisterpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(RegisterpannelLayout.createSequentialGroup()
                                .addGroup(RegisterpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Conpasstext, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Setpasstext, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(RegisterpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(showpass1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(showpass2)))
                            .addGroup(RegisterpannelLayout.createSequentialGroup()
                                .addComponent(REgbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegisterpannelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(291, 291, 291))
        );
        RegisterpannelLayout.setVerticalGroup(
            RegisterpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterpannelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(Registerlable, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(RegisterpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Namelable, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nametext, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(RegisterpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Emaillable)
                    .addComponent(Emailtext, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(RegisterpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Genderpannel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Gendercombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(RegisterpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Phonenolable)
                    .addComponent(Phonetext, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(RegisterpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Usernamepannel)
                    .addComponent(Usernametext, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(RegisterpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegisterpannelLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(showpass1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RegisterpannelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(RegisterpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Setpasspannel)
                            .addComponent(Setpasstext, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32)
                .addGroup(RegisterpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Conpasslable)
                    .addComponent(Conpasstext, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showpass2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(RegisterpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(REgbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        getContentPane().add(Registerpannel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 540, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NametextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NametextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NametextActionPerformed

    private void SetpasstextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SetpasstextActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_SetpasstextActionPerformed

    private void showpass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpass1ActionPerformed
        // TODO add your handling code here:
        if(showpass1.isSelected()){
            Setpasstext.setEchoChar((char) 0); //show password
        }
        else{
            Setpasstext.setEchoChar('*');//Hide Password
         }
    }//GEN-LAST:event_showpass1ActionPerformed

    private void REgbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REgbuttonActionPerformed
        // TODO add your handling code here:
         if(Nametext.getText().equals("")){
                  JOptionPane.showMessageDialog(null, "Please fill out name");
             }else if(Emailtext.getText().equals("")){
                  JOptionPane.showMessageDialog(null, "Please fill out email id");
             }else if (!Emailtext.getText().matches("^[A-Za-z0-9_.-]+@[A-Za-z0-9.-]+$")) {
                  JOptionPane.showMessageDialog(this, "Invalid email format.", "Error", JOptionPane.ERROR_MESSAGE);

             }else if(Setpasstext.getText().equals("")){
                  JOptionPane.showMessageDialog(null, "Please fill out password");
             }else if(Setpasstext.getText().length()<6){
                 JOptionPane.showMessageDialog(null, "atleast 6 characters required in password");
             }
              else if(Phonetext.getText().length()!=10){
                  JOptionPane.showMessageDialog(null, "Invalid phone no");
             }
             else if(Usernametext.getText().equals("")){
                  JOptionPane.showMessageDialog(null, "Please fill out username");
             }
             else if(Conpasstext.getText().equals("")){
                  JOptionPane.showMessageDialog(null,"Please fill out confirm password");
             }
            /* else if(jcpassword1.getText()!=jpassword1.getText()){
                  JOptionPane.showMessageDialog(null, "Mismatch password");
              }*/
             else{
                r.reg();  
             
             }

    }//GEN-LAST:event_REgbuttonActionPerformed

    private void showpass2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpass2ActionPerformed
        // TODO add your handling code here:
        if(showpass2.isSelected()){
            Conpasstext.setEchoChar((char) 0); //show password
        }
        else{
            Conpasstext.setEchoChar('*');//Hide Password
         }
    }//GEN-LAST:event_showpass2ActionPerformed

    private void GendercomboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GendercomboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GendercomboboxActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
          LoginFrame f=new LoginFrame();
        f.show();
        this.dispose();

    }//GEN-LAST:event_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public class registerform{
        private Connection conn ;
        public registerform(){
             connectToDatabase();
        }    
    public void connectToDatabase() {
        try {
            // Load MySQL Driver
            Class.forName("com.mysql.cj.jdbc.Driver");
            // String url = "jdbc:mysql://localhost:3306/?user"; 
            String url = "jdbc:mysql://localhost:3306/SKFARTS?useSSL=false&allowPublicKeyRetrieval=true";  
            String user = "root"; 
            String password = "Harini@05";  

           
            conn = DriverManager.getConnection(url, user, password);
            System.out.println("Connected successfully!");
            JOptionPane.showMessageDialog(null, "Database connected successfully!");

        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, "MySQL JDBC Driver not found!");
            e.printStackTrace();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Database connection failed!\n" + e.getMessage());
            e.printStackTrace();
        }
    }
    
    public void reg(){
        String name=Nametext.getText();
        String username=Usernametext.getText();
        String gmail=Emailtext.getText();
        String phnno=Phonetext.getText();
        String password=new String(Conpasstext.getPassword());
        String gender=Gendercombobox.getSelectedItem().toString();
        String role= "employee";
       
        try{
            String query="insert into users(Name,Email,Gender,Phoneno,Username,Password,Role)values(?,?,?,?,?,?,?)";
            //prepareStatement pt=conn.prepareStatement(query);
            PreparedStatement pt = conn.prepareStatement(query);
            pt.setString(1,name);
            pt.setString(2,gmail);
            pt.setString(3,gender);
            pt.setString(4,phnno);
            pt.setString(5,username);
            pt.setString(6,password);
            pt.setString(7,role);

            pt.executeUpdate();
            JOptionPane.showMessageDialog(null, "registered successfully!");
                   
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Login failed!\n" + e.getMessage());
            e.printStackTrace();
            
        }
    }} 
    

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registeration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registeration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registeration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registeration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registeration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Conpasslable;
    private javax.swing.JPasswordField Conpasstext;
    private javax.swing.JLabel Emaillable;
    private javax.swing.JTextField Emailtext;
    private javax.swing.JComboBox<String> Gendercombobox;
    private javax.swing.JLabel Genderpannel;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel Namelable;
    private javax.swing.JTextField Nametext;
    private javax.swing.JLabel Phonenolable;
    private javax.swing.JTextField Phonetext;
    private javax.swing.JButton REgbutton;
    private javax.swing.JLabel Registerlable;
    private javax.swing.JPanel Registerpannel;
    private javax.swing.JLabel Setpasspannel;
    private javax.swing.JPasswordField Setpasstext;
    private javax.swing.JLabel Usernamepannel;
    private javax.swing.JTextField Usernametext;
    private javax.swing.JPanel backgroundpannel;
    private javax.swing.JCheckBox showpass1;
    private javax.swing.JCheckBox showpass2;
    // End of variables declaration//GEN-END:variables
}
