package miniproject;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import miniproject.ManagerFrame;
import javax.swing.JOptionPane;
import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Date;
import javax.swing.table.DefaultTableModel;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author shreeharini
 */
public class StockManage extends javax.swing.JFrame {
    Stock s=new Stock();
    /**
     * Creates new form StockManage
     */
    public StockManage() {
        initComponents();
        showStock();
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        Heading = new javax.swing.JPanel();
        Stockhead = new javax.swing.JLabel();
        Backbutt = new javax.swing.JButton();
        Proid = new javax.swing.JLabel();
        Proidtext = new javax.swing.JTextField();
        Prodnam = new javax.swing.JLabel();
        Pronamtext = new javax.swing.JTextField();
        Qyt = new javax.swing.JLabel();
        Qyttext = new javax.swing.JTextField();
        Puchdat = new javax.swing.JLabel();
        Pucdattext = new javax.swing.JTextField();
        Deal = new javax.swing.JLabel();
        Cate = new javax.swing.JLabel();
        Catecombo = new javax.swing.JComboBox<>();
        Insertbutt = new javax.swing.JButton();
        Editbutt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Protable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        Delbutt = new javax.swing.JButton();
        Unit = new javax.swing.JLabel();
        Unitcombo = new javax.swing.JComboBox<>();
        Dealcombo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Heading.setBackground(new java.awt.Color(51, 204, 255));
        Heading.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Stockhead.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Stockhead.setText("STOCK MANAGEMENT");
        Heading.add(Stockhead, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, -1, -1));

        Backbutt.setBackground(new java.awt.Color(0, 204, 255));
        Backbutt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Backbutt.setIcon(new javax.swing.ImageIcon("C:\\Users\\aaksh\\Downloads\\icons8-back-48.png")); // NOI18N
        Backbutt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, null));
        Backbutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbuttActionPerformed(evt);
            }
        });
        Heading.add(Backbutt, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 70, 40));

        Background.add(Heading, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 120));

        Proid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Proid.setText("PRODUCT ID");
        Background.add(Proid, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        Proidtext.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Proidtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProidtextActionPerformed(evt);
            }
        });
        Background.add(Proidtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 142, 110, 30));

        Prodnam.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Prodnam.setText("PRODUCT NAME");
        Background.add(Prodnam, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        Pronamtext.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Pronamtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PronamtextActionPerformed(evt);
            }
        });
        Background.add(Pronamtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 110, 30));

        Qyt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Qyt.setText("QUANTITY");
        Background.add(Qyt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        Qyttext.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Qyttext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QyttextActionPerformed(evt);
            }
        });
        Background.add(Qyttext, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 110, 30));

        Puchdat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Puchdat.setText("PURCHASE DATE");
        Background.add(Puchdat, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        Pucdattext.setForeground(new java.awt.Color(204, 204, 204));
        Pucdattext.setText("YYYY-MM-DD");
        Pucdattext.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Pucdattext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PucdattextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PucdattextFocusLost(evt);
            }
        });
        Pucdattext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PucdattextActionPerformed(evt);
            }
        });
        Background.add(Pucdattext, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 90, 30));

        Deal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Deal.setText("DEALER");
        Background.add(Deal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 70, -1));

        Cate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Cate.setText("CATEGORY");
        Background.add(Cate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 80, -1));

        Catecombo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Catecombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SCORING", "LAMINATION", "DESIGN", "PRINTING", " " }));
        Catecombo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Catecombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CatecomboActionPerformed(evt);
            }
        });
        Background.add(Catecombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, 110, -1));

        Insertbutt.setBackground(new java.awt.Color(0, 153, 255));
        Insertbutt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Insertbutt.setText("INSERT");
        Insertbutt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Insertbutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertbuttActionPerformed(evt);
            }
        });
        Background.add(Insertbutt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, 80, 40));

        Editbutt.setBackground(new java.awt.Color(0, 153, 255));
        Editbutt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Editbutt.setText("EDIT");
        Editbutt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Editbutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditbuttActionPerformed(evt);
            }
        });
        Background.add(Editbutt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 630, 100, 40));
        Editbutt.getAccessibleContext().setAccessibleName("jButton");

        Protable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 5));
        Protable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PRO ID", "PRO NAME", "QYT", "PUR DATE", "DEALER", "CATEGORY"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Protable.setShowGrid(true);
        jScrollPane1.setViewportView(Protable);

        Background.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 550, 430));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("  PRODUCT LIST");
        Background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 150, 40));

        Delbutt.setBackground(new java.awt.Color(51, 153, 255));
        Delbutt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Delbutt.setText("DELETE");
        Delbutt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Delbutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelbuttActionPerformed(evt);
            }
        });
        Background.add(Delbutt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 560, 100, 40));

        Unit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Unit.setText("UNIT");
        Background.add(Unit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 50, 30));

        Unitcombo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Unitcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sheets", "Reams", "Liters", "Milliliters", "Pieces", "Sets", "Meters", "Packs", "Rolls", "Grams", "Bottles" }));
        Unitcombo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Background.add(Unitcombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 110, -1));

        Dealcombo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Dealcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Anita", "Meena", "Ram", "Kumar", "Vishal" }));
        Dealcombo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Background.add(Dealcombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 110, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProidtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProidtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProidtextActionPerformed

    private void PronamtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PronamtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PronamtextActionPerformed

    private void QyttextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QyttextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QyttextActionPerformed

    private void EditbuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditbuttActionPerformed
        // TODO add your handling code here:
       try {
        // If product ID field is empty, prompt user to enter a Product ID
        if (Proidtext.getText().trim().isEmpty()) {
            // Ask the user for Product ID
            String productIdInput = JOptionPane.showInputDialog(null, "Enter Product ID to Update:");
            
            // If user entered a valid Product ID
            if (productIdInput != null && !productIdInput.trim().isEmpty()) {
                Connection conn = s.getConnection();
                String sql = "SELECT rname, rquantity, purchase_date, sname, rtype FROM resources WHERE rid=?";
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setInt(1, Integer.parseInt(productIdInput)); // Set the Product ID from dialog input

                ResultSet rs = ps.executeQuery();

                // If the record exists, fetch and populate the fields
                if (rs.next()) {
                    Pronamtext.setText(rs.getString("rname"));
                    Qyttext.setText(String.valueOf(rs.getInt("rquantity")));
                    Pucdattext.setText(rs.getDate("purchase_date").toString());
                    Dealcombo.setSelectedItem(rs.getString("sname"));
                    Catecombo.setSelectedItem(rs.getString("rtype"));
                    JOptionPane.showMessageDialog(null, "Now edit the fields and click Edit again to save changes.");
                } else {
                    JOptionPane.showMessageDialog(null, "Product ID not found.");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Product ID is required.");
            }
        } else {
            // If Product ID is already entered, proceed with the update
            Connection conn = s.getConnection();
            String sql = "UPDATE resources SET rname=?, rquantity=?, purchase_date=?, sname=?, rtype=? WHERE rid=?";
            PreparedStatement ps = conn.prepareStatement(sql);

            // Setting parameters from text fields and combo box
            ps.setString(1, Pronamtext.getText()); // Product Name
            ps.setInt(2, Integer.parseInt(Qyttext.getText())); // Quantity
            ps.setDate(3, java.sql.Date.valueOf(Pucdattext.getText())); // Purchase Date
            ps.setString(4, Dealcombo.getSelectedItem().toString()); // Supplier Name
            ps.setString(5, Catecombo.getSelectedItem().toString()); // Resource Type
            ps.setInt(6, Integer.parseInt(Proidtext.getText())); // Product ID

            // Execute update query
            int rowsAffected = ps.executeUpdate();

            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(null, "Product record updated successfully!");
                showStock(); // Refresh the table display
            } else {
                JOptionPane.showMessageDialog(null, "No matching record found to update.");
            }

            // Clear fields after update
            Proidtext.setText("");
            Pronamtext.setText("");
            Qyttext.setText("");
            Pucdattext.setText("");
            Dealcombo.setSelectedIndex(0);
            Unitcombo.setSelectedIndex(0);
            Catecombo.setSelectedIndex(0);
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Update Error: " + e.getMessage());
    }
    }//GEN-LAST:event_EditbuttActionPerformed

    private void BackbuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbuttActionPerformed
        // TODO add your handling code here:
        this.dispose(); // Close the current frame
    ManagerFrame m = new ManagerFrame(); // Create instance of ManagerFrame
    m.setVisible(true); // Show the Manager frame
    }//GEN-LAST:event_BackbuttActionPerformed

    private void InsertbuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertbuttActionPerformed
        // TODO add your handling code here:
        try {
            Connection conn = s.getConnection();
    String sql = "INSERT INTO resources (rid,rname,rtype,rquantity,unit,purchase_date,sname) VALUES (?, ?, ?, ?, ?, ?,?)";
    PreparedStatement ps = conn.prepareStatement(sql);
    ps.setInt(1, Integer.parseInt( Proidtext.getText()));            
    ps.setString(2, Pronamtext.getText());                         
    ps.setString(3, Catecombo.getSelectedItem().toString());      
    ps.setInt(4, Integer.parseInt(Qyttext.getText()));  
    ps.setString(5, Unitcombo.getSelectedItem().toString());
     // Parse the purchase date from a JTextField (must be in yyyy-MM-dd format)
    ps.setDate(6, java.sql.Date.valueOf(Pucdattext.getText()));
    ps.setString(7, Dealcombo.getSelectedItem().toString());
    ps.executeUpdate();
    JOptionPane.showMessageDialog(null, "Resource added successfully!");
    showStock();
   Proidtext .setText("");
Pronamtext.setText("");
Qyttext.setText("");
Pucdattext.setText("");
Dealcombo.setSelectedIndex(0);
Unitcombo.setSelectedIndex(0);
Catecombo.setSelectedIndex(0);
} catch (Exception e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
}

    }//GEN-LAST:event_InsertbuttActionPerformed

    private void CatecomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CatecomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CatecomboActionPerformed

    private void DelbuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelbuttActionPerformed
       try {
        // Prompt the user for Product ID
        String productIdInput = JOptionPane.showInputDialog(null, "Enter Product ID to Delete:");

        // If user enters a valid Product ID
        if (productIdInput != null && !productIdInput.trim().isEmpty()) {
            // Parse the Product ID from the input
            int productId = Integer.parseInt(productIdInput);
            
            // Establish connection
            Connection conn = s.getConnection();
            String sql = "DELETE FROM resources WHERE rid=?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setInt(1, productId); // Set the Product ID from the dialog input

            // Execute the delete query
            int rowsAffected = ps.executeUpdate();

            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(null, "Product deleted successfully!");
                showStock(); // Refresh the table display
            } else {
                JOptionPane.showMessageDialog(null, "Product ID not found.");
            }

            // Clear the text fields after deletion
            Proidtext.setText("");
            Pronamtext.setText("");
            Qyttext.setText("");
            Pucdattext.setText("");
            Dealcombo.setSelectedIndex(0);
            Unitcombo.setSelectedIndex(0);
            Catecombo.setSelectedIndex(0);
        } else {
            JOptionPane.showMessageDialog(null, "Product ID is required.");
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Delete Error: " + e.getMessage());
    }
    }//GEN-LAST:event_DelbuttActionPerformed

    private void PucdattextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PucdattextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PucdattextActionPerformed

    private void PucdattextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PucdattextFocusGained
        // TODO add your handling code here:
        if(Pucdattext.getText().equals("YYYY-MM-DD")){
            Pucdattext.setText("");
            Pucdattext.setForeground(Color.BLACK);
        }

    }//GEN-LAST:event_PucdattextFocusGained

    private void PucdattextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PucdattextFocusLost
        // TODO add your handling code here:
         if(Pucdattext.getText().isEmpty()){
            Pucdattext.setText("YYYY-MM-DD");
            Pucdattext.setForeground(Color.GRAY);
         }

    }//GEN-LAST:event_PucdattextFocusLost

    private void showStock() {
        try{
             Connection conn = s.getConnection();
        String sql = "SELECT * FROM resources";
        PreparedStatement ps = conn.prepareStatement(sql);
        ResultSet rs = ps.executeQuery();

        DefaultTableModel model = (DefaultTableModel) Protable.getModel();
        model.setRowCount(0); // Clear table first

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("rid"),
                rs.getString("rname"),
                rs.getInt("rquantity"),
                rs.getDate("purchase_date"),
                rs.getString("sname"),
                rs.getString("rtype")
            });
        }
     
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Display Error: " + e.getMessage());
    }
}
 public class Stock{
        private Connection conn ;
        public Stock(){
             connectToDatabase();
        }    
    public void connectToDatabase() {
        try {
            // Load MySQL Driver
            Class.forName("com.mysql.cj.jdbc.Driver");
            // String url = "jdbc:mysql://localhost:3306/?user"; 
            String url = "jdbc:mysql://localhost:3306/SKFARTS?useSSL=false&allowPublicKeyRetrieval=true";  
            String user = "root"; 
            String password = "Harini@05";  

           
            conn = DriverManager.getConnection(url, user, password);
            System.out.println("Connected successfully!");
            JOptionPane.showMessageDialog(null, "Database connected successfully!");

        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, "MySQL JDBC Driver not found!");
            e.printStackTrace();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Database connection failed!\n" + e.getMessage());
            e.printStackTrace();
        }
    }
    public Connection getConnection() {
        return conn;
    }
 }/**
     * @param args the command line arguments
     */
 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StockManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StockManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StockManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StockManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StockManage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Backbutt;
    private javax.swing.JPanel Background;
    private javax.swing.JLabel Cate;
    private javax.swing.JComboBox<String> Catecombo;
    private javax.swing.JLabel Deal;
    private javax.swing.JComboBox<String> Dealcombo;
    private javax.swing.JButton Delbutt;
    private javax.swing.JButton Editbutt;
    private javax.swing.JPanel Heading;
    private javax.swing.JButton Insertbutt;
    private javax.swing.JLabel Prodnam;
    private javax.swing.JLabel Proid;
    private javax.swing.JTextField Proidtext;
    private javax.swing.JTextField Pronamtext;
    private javax.swing.JTable Protable;
    private javax.swing.JTextField Pucdattext;
    private javax.swing.JLabel Puchdat;
    private javax.swing.JLabel Qyt;
    private javax.swing.JTextField Qyttext;
    private javax.swing.JLabel Stockhead;
    private javax.swing.JLabel Unit;
    private javax.swing.JComboBox<String> Unitcombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
