/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package miniproject;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import miniproject.ManagerFrame;
import javax.swing.JOptionPane;
import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Date;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author shreeharini
 */
public class Stockmanage1 extends javax.swing.JFrame {
          Stocks s=new Stocks();
        private Connection conn;
    /**
     * Creates new form Stockmanage1
     */
    public Stockmanage1() {
        initComponents();
        showStock();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Backgroundpan = new javax.swing.JPanel();
        Heading = new javax.swing.JPanel();
        Stockhead = new javax.swing.JLabel();
        Backbutt = new javax.swing.JButton();
        Proid = new javax.swing.JLabel();
        Proidtext = new javax.swing.JTextField();
        Prodnam = new javax.swing.JLabel();
        Pronamtext = new javax.swing.JTextField();
        Qyt = new javax.swing.JLabel();
        Qyttext = new javax.swing.JTextField();
        Puchdat = new javax.swing.JLabel();
        Pucdattext = new javax.swing.JTextField();
        Deal = new javax.swing.JLabel();
        Cate = new javax.swing.JLabel();
        Catecombo = new javax.swing.JComboBox<>();
        Editbutt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Protable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        Unit = new javax.swing.JLabel();
        Unitcombo = new javax.swing.JComboBox<>();
        Dealcombo = new javax.swing.JComboBox<>();

        Backgroundpan.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout BackgroundpanLayout = new javax.swing.GroupLayout(Backgroundpan);
        Backgroundpan.setLayout(BackgroundpanLayout);
        BackgroundpanLayout.setHorizontalGroup(
            BackgroundpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
        );
        BackgroundpanLayout.setVerticalGroup(
            BackgroundpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 567, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Heading.setBackground(new java.awt.Color(51, 204, 255));
        Heading.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Stockhead.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Stockhead.setText("STOCK MANAGEMENT");
        Heading.add(Stockhead, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, -1, -1));

        Backbutt.setBackground(new java.awt.Color(0, 204, 255));
        Backbutt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Backbutt.setIcon(new javax.swing.ImageIcon("C:\\Users\\aaksh\\Downloads\\icons8-back-48.png")); // NOI18N
        Backbutt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, null));
        Backbutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbuttActionPerformed(evt);
            }
        });
        Heading.add(Backbutt, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 70, 40));

        Proid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Proid.setText("PRODUCT ID");

        Proidtext.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Proidtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProidtextActionPerformed(evt);
            }
        });

        Prodnam.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Prodnam.setText("PRODUCT NAME");

        Pronamtext.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Pronamtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PronamtextActionPerformed(evt);
            }
        });

        Qyt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Qyt.setText("QUANTITY");

        Qyttext.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Qyttext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QyttextActionPerformed(evt);
            }
        });

        Puchdat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Puchdat.setText("PURCHASE DATE");

        Pucdattext.setForeground(new java.awt.Color(204, 204, 204));
        Pucdattext.setText("YYYY-MM-DD");
        Pucdattext.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Pucdattext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PucdattextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PucdattextFocusLost(evt);
            }
        });
        Pucdattext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PucdattextActionPerformed(evt);
            }
        });

        Deal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Deal.setText("DEALER");

        Cate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Cate.setText("CATEGORY");

        Catecombo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Catecombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SCORING", "LAMINATION", "DESIGN", "PRINTING", " " }));
        Catecombo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Catecombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CatecomboActionPerformed(evt);
            }
        });

        Editbutt.setBackground(new java.awt.Color(0, 153, 255));
        Editbutt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Editbutt.setText("EDIT");
        Editbutt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Editbutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditbuttActionPerformed(evt);
            }
        });

        Protable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 5));
        Protable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PRO ID", "PRO NAME", "QYT", "PUR DATE", "DEALER", "CATEGORY"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Protable.setShowGrid(true);
        jScrollPane1.setViewportView(Protable);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("  PRODUCT LIST");

        Unit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Unit.setText("UNIT");

        Unitcombo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Unitcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sheets", "Reams", "Liters", "Milliliters", "Pieces", "Sets", "Meters", "Packs", "Rolls", "Grams", "Bottles" }));
        Unitcombo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        Dealcombo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Dealcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Anita", "Meena", "Ram", "Kumar", "Vishal" }));
        Dealcombo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(207, 207, 207))
            .addGroup(layout.createSequentialGroup()
                .addComponent(Heading, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(Editbutt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Cate, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Unit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Deal, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Dealcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Unitcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Catecombo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Proid)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Proidtext, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Puchdat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Pucdattext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Qyt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Qyttext, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Prodnam)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Pronamtext, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Heading, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Proid)
                            .addComponent(Proidtext, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Prodnam)
                            .addComponent(Pronamtext, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Qyt)
                            .addComponent(Qyttext, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Pucdattext, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Puchdat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Deal)
                            .addComponent(Dealcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Unit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Unitcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Cate)
                            .addComponent(Catecombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(Editbutt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackbuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbuttActionPerformed
        // TODO add your handling code here:
        this.dispose(); // Close the current frame
        EmployeeFrame m = new EmployeeFrame(); // Create instance of ManagerFrame
        m.setVisible(true); // Show the Manager frame
    }//GEN-LAST:event_BackbuttActionPerformed

    private void ProidtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProidtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProidtextActionPerformed

    private void PronamtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PronamtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PronamtextActionPerformed

    private void QyttextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QyttextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QyttextActionPerformed

    private void PucdattextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PucdattextFocusGained
        // TODO add your handling code here:
           if(Pucdattext.getText().equals("YYYY-MM-DD")){
            Pucdattext.setText("");
            Pucdattext.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_PucdattextFocusGained

    private void PucdattextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PucdattextFocusLost
        // TODO add your handling code here:
           if(Pucdattext.getText().isEmpty()){
            Pucdattext.setText("YYYY-MM-DD");
            Pucdattext.setForeground(Color.GRAY);
           }

    }//GEN-LAST:event_PucdattextFocusLost

    private void PucdattextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PucdattextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PucdattextActionPerformed

    private void CatecomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CatecomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CatecomboActionPerformed

    private void EditbuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditbuttActionPerformed
try {
        // If product ID field is empty, prompt user to enter a Product ID
        if (Proidtext.getText().trim().isEmpty()) {
            // Ask the user for Product ID
            String productIdInput = JOptionPane.showInputDialog(null, "Enter Product ID to Update:");
            
            // If user entered a valid Product ID
            if (productIdInput != null && !productIdInput.trim().isEmpty()) {
                Connection conn = s.getConnection();
                String sql = "SELECT rname, rquantity, purchase_date, sname, rtype FROM resources WHERE rid=?";
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setInt(1, Integer.parseInt(productIdInput)); // Set the Product ID from dialog input

                ResultSet rs = ps.executeQuery();

                // If the record exists, fetch and populate the fields
                if (rs.next()) {
                    Pronamtext.setText(rs.getString("rname"));
                    Qyttext.setText(String.valueOf(rs.getInt("rquantity")));
                    Pucdattext.setText(rs.getDate("purchase_date").toString());
                    Dealcombo.setSelectedItem(rs.getString("sname"));
                    Catecombo.setSelectedItem(rs.getString("rtype"));
                    JOptionPane.showMessageDialog(null, "Now edit the fields and click Edit again to save changes.");
                } else {
                    JOptionPane.showMessageDialog(null, "Product ID not found.");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Product ID is required.");
            }
        } else {
            // If Product ID is already entered, proceed with the update
            Connection conn = s.getConnection();
            String sql = "UPDATE resources SET rname=?, rquantity=?, purchase_date=?, sname=?, rtype=? WHERE rid=?";
            PreparedStatement ps = conn.prepareStatement(sql);

            // Setting parameters from text fields and combo box
            ps.setString(1, Pronamtext.getText()); // Product Name
            ps.setInt(2, Integer.parseInt(Qyttext.getText())); // Quantity
            ps.setDate(3, java.sql.Date.valueOf(Pucdattext.getText())); // Purchase Date
            ps.setString(4, Dealcombo.getSelectedItem().toString()); // Supplier Name
            ps.setString(5, Catecombo.getSelectedItem().toString()); // Resource Type
            ps.setInt(6, Integer.parseInt(Proidtext.getText())); // Product ID

            // Execute update query
            int rowsAffected = ps.executeUpdate();

            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(null, "Product record updated successfully!");
                showStock(); // Refresh the table display
            } else {
                JOptionPane.showMessageDialog(null, "No matching record found to update.");
            }

            // Clear fields after update
            Proidtext.setText("");
            Pronamtext.setText("");
            Qyttext.setText("");
            Pucdattext.setText("");
            Dealcombo.setSelectedIndex(0);
            Unitcombo.setSelectedIndex(0);
            Catecombo.setSelectedIndex(0);
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Update Error: " + e.getMessage());
    }
    }//GEN-LAST:event_EditbuttActionPerformed

    private void showStock() {
        try{
         Connection conn = s.getConnection();
        String sql = "SELECT * FROM resources";
        PreparedStatement ps = conn.prepareStatement(sql);
        ResultSet rs = ps.executeQuery();

        DefaultTableModel model = (DefaultTableModel) Protable.getModel();
        model.setRowCount(0); // Clear table first

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("rid"),
                rs.getString("rname"),
                rs.getInt("rquantity"),
                rs.getDate("purchase_date"),
                rs.getString("sname"),
                rs.getString("rtype")
            });
        }
     
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Display Error: " + e.getMessage());
    }
}
   public class Stocks {
    private Connection conn;

    public Stocks() {
        connectToDatabase();
    }

    public void connectToDatabase() {
        try {
            // Load MySQL Driver
            Class.forName("com.mysql.cj.jdbc.Driver");

            String url = "jdbc:mysql://localhost:3306/SKFARTS?useSSL=false&allowPublicKeyRetrieval=true";  
            String user = "root"; 
            String password = "Harini@05";  

            conn = DriverManager.getConnection(url, user, password);
            System.out.println("Connected successfully!");
            JOptionPane.showMessageDialog(null, "Database connected successfully!");

        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, "MySQL JDBC Driver not found!");
            e.printStackTrace();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Database connection failed!\n" + e.getMessage());
            e.printStackTrace();
        }
    }

    public Connection getConnection() {
        return conn;
    }
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stockmanage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stockmanage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stockmanage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stockmanage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Stockmanage1().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Backbutt;
    private javax.swing.JPanel Backgroundpan;
    private javax.swing.JLabel Cate;
    private javax.swing.JComboBox<String> Catecombo;
    private javax.swing.JLabel Deal;
    private javax.swing.JComboBox<String> Dealcombo;
    private javax.swing.JButton Editbutt;
    private javax.swing.JPanel Heading;
    private javax.swing.JLabel Prodnam;
    private javax.swing.JLabel Proid;
    private javax.swing.JTextField Proidtext;
    private javax.swing.JTextField Pronamtext;
    private javax.swing.JTable Protable;
    private javax.swing.JTextField Pucdattext;
    private javax.swing.JLabel Puchdat;
    private javax.swing.JLabel Qyt;
    private javax.swing.JTextField Qyttext;
    private javax.swing.JLabel Stockhead;
    private javax.swing.JLabel Unit;
    private javax.swing.JComboBox<String> Unitcombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
